version: '3'

services: 

  server:
    build: 
      context: server
    container_name: server
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "3000:3000"
    command: npm run start

  client:
    build: 
      context: client
    container_name: client
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "5173:5173"
    command: npm run dev

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
       - server
       - client
  
networks: 
  node-network:
    driver: bridge